# Generated by Django 2.2.4 on 2019-09-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bariwalar_nam', models.CharField(max_length=100)),
                ('zilla', models.CharField(max_length=50)),
                ('upazilla', models.CharField(max_length=50)),
                ('elaka', models.CharField(max_length=50)),
            ],
        ),
    ]
