# Generated by Django 2.2.4 on 2019-09-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='shobar_ghorer_shonkhya',
            new_name='shobar_ghorer_shongkhya',
        ),
    ]
