# Generated by Django 2.2.4 on 2019-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190905_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bariwalar_reg_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='family_basha',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathroomer_shongkhya',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='khabar_ghor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rannaghor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='shobar_ghorer_shonkhya',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='barivara',
            field=models.IntegerField(null=True),
        ),
    ]
