# Generated by Django 2.2.4 on 2019-09-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190906_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='vara',
            new_name='barivara',
        ),
    ]
