# Generated by Django 2.2.4 on 2019-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20190905_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='elaka',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='house',
            name='upazilla',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='house',
            name='zilla',
            field=models.CharField(max_length=25),
        ),
    ]
