# Generated by Django 2.2.4 on 2019-09-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20190905_2215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='House',
        ),
    ]
