# Generated by Django 2.2.4 on 2019-09-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20190905_2215'),
        ('houses', '0003_auto_20190906_1216'),
    ]

    operations = [
    ]
