# Generated by Django 2.2.4 on 2019-09-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_merge_20190906_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='shobar_ghorer_shonkhya',
        ),
        migrations.RemoveField(
            model_name='house',
            name='vara',
        ),
        migrations.AlterModelTable(
            name='house',
            table='House',
        ),
    ]
