# Generated by Django 2.2.4 on 2019-09-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20190906_1536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table=None,
        ),
    ]
