# Generated by Django 2.2.4 on 2019-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20190906_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
